server-id: "No Name"
server-desc: "No Description Provided"
enable-ads: true
max-players: 5
restart-delay: 30000
pvp: false

commands:
  sharelocation:
    enabled: true
    permission: ""
  ping:
    enabled: true
    permission: ""
  craft:
    enabled: false
    permission: ""
  enchant:
    enabled: false
    permission: ""
