server-id: "No Name"
server-desc: "No Description Provided"
enable-ads: true
max-players: 5

restart-warn-delay: 30
restart-delay: 30000

# PVP Related
pvp: true
custom-pvp-messages: true

# Custom Util Features
custom-motd: true
verbose-welcome: true

# Configurable Commands
commands:
  sharelocation:
    enabled: true
    permission: ""
  ping:
    enabled: true
    permission: ""
  craft:
    enabled: false
    permission: ""
  enchant:
    enabled: false
    permission: ""
