name: Survival
version: '${project.version}'
main: com.amirparsa.survival.Survival
api-version: '1.16'
commands:
  ping:
    usage: /<command> [name]
    description: See Your Or Others Ping
  sharelocation:
    usage: /<command> PlayerName
    description: Share Your Location With The Specified Player
    aliases: [ sl ]
  craft:
    usage: /<command>
    description: Opens The Crafting Table
  enchant:
    usage: /<command>
    description: Opens The Enchanting Table
